# Generated by Django 4.1.6 on 2023-02-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=20)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.TextField(max_length=200)),
                ('item_history', models.TextField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
