# Generated by Django 4.1.6 on 2023-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_owner_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_sumup',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
