# Generated by Django 4.1.6 on 2023-02-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_item_actions_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_history',
        ),
    ]
