# Generated by Django 4.1.6 on 2023-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_item_item_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_history',
            field=models.TextField(default=''),
        ),
    ]
