# Generated by Django 4.1.6 on 2023-02-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_sumup',
        ),
    ]
