# Generated by Django 4.1.6 on 2023-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_item_item_sumup'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_last_action',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_history',
            field=models.TextField(default='', null=True),
        ),
    ]
