# Generated by Django 4.1.6 on 2023-03-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_item_item_last_action_alter_item_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hash',
        ),
    ]
